fixed small bug with class Item
r-dent/EliminationMenu pull request #1
Opened 2016-09-14 19:15 UTC by Osuka42g

2016-09-21 12:07 UTC, r-dent commented on Sources/EliminationMenu.swift
> +                item: view, attribute: .LeftMargin, relatedBy: .Equal, toItem: menu, attribute: .Left, multiplier: 1, constant: margin.x)
Changing of `view` and `menu` would reintroduce the bug i fixed in [this Commit](https://github.com/r-dent/EliminationMenu/commit/11973b8bbd3dbda6f76d5c2268c7f3bcaac6d9bb), i think. (the menu was not inset but "outset" of the containing view.)

2016-09-21 12:09 UTC, r-dent commented on Sources/EliminationMenu.swift
> +                item: view, attribute: .RightMargin, relatedBy: .Equal, toItem: menu, attribute: .Right, multiplier: 1, constant: margin.x)
I pinned the edges to the view on purpose to [provide compatibility to iOS 7](https://github.com/r-dent/EliminationMenu/commit/16f6f638e8e39c3f8080ac80416ee9b82131405c). Thought that would be a good Idea :-)

2016-09-21 12:11 UTC, r-dent commented on Sources/EliminationMenu.swift
> +        public init(value value:AnyObject, title: String = "", icon: UIImage? = nil) {
I think the fix is the missing `public` right?

2016-09-21 12:13 UTC, r-dent requested changes
If the fix is just the missing `public` declaration, maybe you remove the other changes. I would merge it then.

2016-09-21 15:23 UTC, Osuka42g commented
Thank you for the feedback r-dent!
I'm making some other modifications, including swift 3 support. I expect to make another pull request soon, also taking in consideration that you told me.

2016-10-25 09:07 UTC, r-dent commented
I´m closing this as i think it´s deprecated yet.

2016-10-25 09:07 UTC, closed without merging